### ISSUE TITLE
Higher FPS.

### ISSUE THREAD

**Issue by blmhemu** [AlfredoSequeida/fvid#3]
I see that currently only 1 frame is changed per 5 seconds. I was wondering the reason behind this choice. Also is it possible to encode it to higher frames per second ?

**Comment by ThatIsAPseudo** [comment]
I'd say it's to make sure there are enough frames of the same image (at 30 fps, if "only 1 frame is changed per 5 seconds" that makes 6 times the same image), so that the middle one (the 3rd/4th) is the closest to the original one. (Or the average of the 6 frames is closer to the original)

I guess if you make a 60 fps video, video encoding + youtube compression can make a white pixel temporally surrounded by black ones so dark that it's closer to black than white (and vice-versa). 
While if you force the same image several frames in a row there's less risk to get corrupted data eventually.

However, error correction (e.g. Hamming code) could be implemented so that we can achieve the most efficient (original file size) / (video file size) ratio.

I'm not the author though and I barely looked at the code yet, so I may/must be mistaking.

**Comment by misaalanshori** [comment]
What if the size of the bits is bigger (eg 2x2 instead of 1 pixel), but we increase the framerate? I feel like if balanced just right that could really increase the amount of data stored per video length

**Comment by AlfredoSequeida** [comment]
@blmhemu Good question, the reason behind that was simply to reduce the file size. As you might have noticed, smaller files like a text file or image get a lot bigger after making them into videos - just by the nature of it being a video and containing more data. 

So the point behind that was to keep file sizes as small as possible. I could definetly add a feture to allow for cutom fps though. Keep in mind that for single frames - YouTube will not let you upload a file that is less than 1 second. At least that is what I found was the case during testing. YouTube just refuses to process the file and quite the upload process.

**Comment by AlfredoSequeida** [comment]
@Theelgirl fixed/enhanced this with #12
